[build]
  publish = "frontend"
  command = "# команда сборки, если требуется"

[[redirects]]
  from = "/auth/*"
  to = "https://api.foodtrack.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
