blank_issues_enabled: false
contact_links:
  - name: Обсуждения
    url: https://github.com/RobertUptodateman/FoodTrack/discussions
    about: Для общих вопросов и обсуждений используйте раздел Discussions
