name: Project Automation

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  project_automation:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue or PR to correct column
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: FoodTrack Development
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: add
