name: "Convert TODOs to Issues"

on:
  push:
    branches: [ master ]

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.3
        id: todo
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "todo"
          COMMENT_MARKER: "TODO:"
